name: Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

concurrency:
  group: homeserver-health-check-terraform
  cancel-in-progress: false

jobs:
  terraform:
    uses: KandlerLi/gha-common/.github/workflows/terraform-apply.yml@v0.0.13
    with:
      aws_region: us-east-1
    secrets: inherit
